canteenapp/config/routes.rb
Rails.application.routes.draw do
  get 'price/page'

  resources :orders
  resources :sumnes
  root 'store#index'

  resources :line_items
  resources :carts
  resources :menus
  root 'home#page'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

canteenapp/app/models/menu.rb
class Menu < ApplicationRecord
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  has_many :orders

  mount_uploader :picture, MenuPictureUploader

  def self.latest
    Menu.order(:updated_at).last
  end
  private

    def ensure_not_referenced_by_any_line_item
      unless line_items.empty?
        errors.add(:base,'Line Items Present')
        throw :abort
      end
    end

    def exists?
      if @menu
        return true
      end
    end
end

canteenapp/app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:name, :category, :avaialability, :price, :picture)
    end
end

canteenapp/app/helpers/menus_helper.rb
module MenusHelper
end

canteenapp/app/views/menus/_form.html.erb
<%= simple_form_for(@menu) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :category, collection: [:Burger,:Pizza,:Drinks] %>
    <%= f.input :avaialability %>
    <%= f.input :price %>
    <%= f.input :picture, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

canteenapp/app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

canteenapp/app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menus</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Avaialability</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @menus.exists? %>
      <% @menus.each do |menu| %>
        <tr>
          <td><%= menu.name %></td>
          <td><%= menu.category %></td>
          <td><%= menu.avaialability ? 'YES' : 'NO' %> </td>
          <td><%= menu.price %></td>
          <td><%= link_to 'Show', menu %></td>
          <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
          <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% else %>
      <p> Item not available </p>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

canteenapp/app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

canteenapp/app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @menu.category %>
</p>

<p>
  <strong>Avaialability:</strong>
  <%= @menu.avaialability %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu.price %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>