canteenapp/config/routes.rb
Rails.application.routes.draw do
  get 'price/page'

  resources :orders
  resources :sumnes
  root 'store#index'

  resources :line_items
  resources :carts
  resources :menus
  root 'home#page'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

canteenapp/app/models/sumne.rb
class Sumne < ApplicationRecord
  mount_uploader :picture,MenuPictureUploader
end

canteenapp/app/controllers/sumnes_controller.rb
class SumnesController < ApplicationController
  before_action :set_sumne, only: [:show, :edit, :update, :destroy]

  # GET /sumnes
  # GET /sumnes.json
  def index
    @sumnes = Sumne.all
  end

  # GET /sumnes/1
  # GET /sumnes/1.json
  def show
  end

  # GET /sumnes/new
  def new
    @sumne = Sumne.new
  end

  # GET /sumnes/1/edit
  def edit
  end

  # POST /sumnes
  # POST /sumnes.json
  def create
    @sumne = Sumne.new(sumne_params)

    respond_to do |format|
      if @sumne.save
        format.html { redirect_to @sumne, notice: 'Sumne was successfully created.' }
        format.json { render :show, status: :created, location: @sumne }
      else
        format.html { render :new }
        format.json { render json: @sumne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sumnes/1
  # PATCH/PUT /sumnes/1.json
  def update
    respond_to do |format|
      if @sumne.update(sumne_params)
        format.html { redirect_to @sumne, notice: 'Sumne was successfully updated.' }
        format.json { render :show, status: :ok, location: @sumne }
      else
        format.html { render :edit }
        format.json { render json: @sumne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sumnes/1
  # DELETE /sumnes/1.json
  def destroy
    @sumne.destroy
    respond_to do |format|
      format.html { redirect_to sumnes_url, notice: 'Sumne was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sumne
      @sumne = Sumne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sumne_params
      params.require(:sumne).permit(:name, :price, :ingredients,:picture)
    end
end

canteenapp/app/helpers/sumnes_helper.rb
module SumnesHelper
end

canteenapp/app/views/sumnes/_form.html.erb
<%= simple_form_for(@sumne) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :ingredients %>
    <%= f.input :picture,as: :file%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

canteenapp/app/views/sumnes/edit.html.erb
<h1>Editing Sumne</h1>

<%= render 'form', sumne: @sumne %>

<%= link_to 'Show', @sumne %> |
<%= link_to 'Back', sumnes_path %>

canteenapp/app/views/sumnes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sumnes</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Ingredients</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sumnes.each do |sumne| %>
      <tr>
        <td><%= sumne.name %></td>
        <td><%= sumne.price %></td>
        <td><%= sumne.ingredients %></td>
        <td><%= link_to 'Show', sumne %></td>
        <td><%= link_to 'Edit', edit_sumne_path(sumne) %></td>
        <td><%= link_to 'Destroy', sumne, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sumne', new_sumne_path %>

canteenapp/app/views/sumnes/new.html.erb
<h1>New Sumne</h1>

<%= render 'form', sumne: @sumne %>

<%= link_to 'Back', sumnes_path %>

canteenapp/app/views/sumnes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sumne.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @sumne.price %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @sumne.ingredients %>
</p>

<p>
  <%= image_tag(@sumne.picture) %>
</p>


<%= link_to 'Edit', edit_sumne_path(@sumne) %> |
<%= link_to 'Back', sumnes_path %>